name: pull-request test build

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup go environment
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false

      - name: verify dependencies
        run: |
          go mod verify
          go mod tidy
          git diff --exit-code go.mod go.sum || (echo "go.mod or go.sum changed unexpectedly"; exit 1)

      - name: go unit tests
        run: |
          make unit-tests

      - name: golangci-lint
        run: |
          make lint

      - name: trivy scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          format: table
          scan-ref: .
          severity: MEDIUM,HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1
